workflow_assignment.workflow_list.schema:
  type: config_entity
  label: 'Workflow List'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'UUID'
    status:
      type: boolean
      label: 'Status'
    description:
      type: text
      label: 'Description'
    assigned_users:
      type: sequence
      label: 'Assigned Users'
      sequence:
        type: integer
        label: 'User ID'
    assigned_groups:
      type: sequence
      label: 'Assigned Groups'
      sequence:
        type: integer
        label: 'Group ID'
    resource_tags:
      type: sequence
      label: 'Resource Location Tags'
      sequence:
        type: integer
        label: 'Term ID'
    created:
      type: timestamp
      label: 'Created'
    changed:
      type: timestamp
      label: 'Changed'

workflow_assignment.settings:
  type: config_object
  label: 'Workflow Assignment settings'
  mapping:
    allowed_content_types:
      type: sequence
      label: 'Allowed content types'
      sequence:
        type: string
        label: 'Content type'
    resource_vocabulary:
      type: string
      label: 'Resource location vocabulary'
